services:
  - type: pserv
    name: erpnext-db
    plan: free
    runtime: image
    image:
      url: mariadb:10.6
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true
      - key: MYSQL_DATABASE
        value: erpnext

  - type: pserv
    name: erpnext-redis-cache
    plan: free
    runtime: image
    image:
      url: redis:6.2-alpine
    envVars:
      - key: REDIS_PASSWORD
        generateValue: true

  - type: web
    name: erpnext-app
    plan: free
    runtime: image
    image:
      url: frappe/erpnext:v15
    envVars:
      - key: DB_HOST
        fromService:
          name: erpnext-db
          type: pserv
          property: host
      - key: DB_PASSWORD
        fromService:
          name: erpnext-db
          type: pserv
          property: connectionString
          prefix: "mysql://root:"
          suffix: "@"
      - key: REDIS_PASSWORD
        fromService:
          name: erpnext-redis-cache
          type: pserv
          property: connectionString
          prefix: "redis://default:"
          suffix: "@"
      - key: MARIADB_HOST
        fromService:
          name: erpnext-db
          type: pserv
          property: host
      - key: REDIS_CACHE
        fromService:
          name: erpnext-redis-cache
          type: pserv
          property: connectionString
      - key: REDIS_QUEUE
        fromService:
          name: erpnext-redis-cache
          type: pserv
          property: connectionString
      - key: REDIS_SOCKETIO
        fromService:
          name: erpnext-redis-cache
          type: pserv
          property: connectionString
